services:
  - type: web
    name: perpustakaan-app
    env: python
    buildCommand: "./build.sh"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: perpustakaan-db
          property: connectionString
  - type: pserv
    name: perpustakaan-db
    env: postgres
    plan: free
    ipAllowList: []
